draw_config:
  glyph_tap_size: 18
  svg_extra_style: |
    rect.held { fill: #ba4e47; }
parse_config:
  raw_binding_map:
    "&mo 1": {t: "left", type: held}
    "&mo 2": {t: "right", type: held}
    "&kp BACKSPACE": {t: "$$mdi:backspace$$"}
    "&studio_unlock": {t: "ZMK"}
    "&kp LC(BSPC)": {t: "$$mdi:backspace$$", h: "Ctl"}
    "&kp LS(N2)": {t: "@"}
    "&kp LS(FSLH)": {t: "?"}
    "&kp PRINTSCREEN": {t: "PRTSC"}
    "&kp C_PP": {t: "$$mdi:play-pause$$"}
    "&kp C_PREV": {t: "$$mdi:skip-previous$$"}
    "&kp C_NEXT": {t: "$$mdi:skip-next$$"}
    "&kp C_VOL_UP": {t: "$$mdi:volume-high$$"}
    "&kp C_VOL_DN": {t: "$$mdi:volume-low$$"}
    "&kp C_MUTE": {t: "$$mdi:volume-mute$$"}
    "&kp UP": {t: "$$mdi:arrow-up$$"}
    "&kp DOWN": {t: "$$mdi:arrow-down$$"}
    "&kp LEFT": {t: "$$mdi:arrow-left$$"}
    "&kp RIGHT": {t: "$$mdi:arrow-right$$"}
    "&kp ENTER": {t: "$$mdi:keyboard-return$$"}
    "&kp TAB": {t: "$$mdi:keyboard-tab$$"}
    "&kp SPACE": {t: "$$mdi:keyboard-space$$"}
    "&kp CAPS": {t: "$$mdi:keyboard-caps$$"}
    "&kp LSHFT": {t: "$$mdi:apple-keyboard-shift$$"}
    "&kp RSHFT": {t: "$$mdi:apple-keyboard-shift$$"}
    "&kp DELETE": {t: "$$mdi:backspace-reverse-outline$$"}
    "&kp LGUI": {t: "$$mdi:microsoft-windows$$"}
    "&kp RGUI": {t: "$$mdi:microsoft-windows$$"}
